### ISSUE TITLE
Дубли объектов Pool на Hitachi

### ISSUE THREAD

**Issue by Andreyspro** [ComputerPers/StorageInventory_BUGS#27]
На массивах Hitachi некоторые объекты Pool дублируются.
![image](https://user-images.githubusercontent.com/28852205/123047487-04c76200-d406-11eb-879a-3dea70d4ca94.png)
![image](https://user-images.githubusercontent.com/28852205/123047688-42c48600-d406-11eb-9177-2eaa212e2c61.png)

**Comment by ComputerPers** [comment]
Storage-Inventory-v2.xlsx проблема в этом файле.

**Comment by ComputerPers** [comment]
Починено в версии сборщика 2.41
