### ISSUE TITLE
В колонке InfoSystem много не заполненных значений.

### ISSUE THREAD

**Issue by Andreyspro** [ComputerPers/StorageInventory_BUGS#32]
В колонке InfoSystem много не заполненных значений на закладке HostGroups, Luns, Pools/
![image](https://user-images.githubusercontent.com/28852205/129130999-3fe0203a-8326-4e66-9f7f-36449e71bb3b.png)

**Comment by ComputerPers** [comment]
Данное поле заполняется от имен объектов, которое должно быть сделано по стандарту именования
Парити группы не могут иметь названий, соответственно их невозможно никак идентифицировать.

Не будет сделано.
